server {
    listen 80;

    # Forward /l3gl/* vers l'Ingress de Minikube
    location /l3gl/ {
        proxy_pass http://192.168.49.2/;  # IP de Minikube
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    # Optionnel : gestion des erreurs
    error_page 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}