apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: devops-l3gl
data:
  default.conf: |
    server {
        listen 80;
        location /l3gl/ {
            proxy_pass http://task-api-service:8085/;
        }
    }

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: devops-l3gl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-conf
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-conf
        configMap:
          name: nginx-config

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: devops-l3gl
spec:
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: l3gl-ingress
  namespace: devops-l3gl
spec:
  rules:
  - http:
      paths:
      - path: /l3gl/
        pathType: Prefix
        backend:
          service:
            name: nginx-service
            port:
              number: 80