# /etc/nginx/sites-available/l3gl.conf
server {
    listen 80;

    server_name _;

    # Gestion des logs
    access_log /var/log/nginx/l3gl.access.log;
    error_log /var/log/nginx/l3gl.error.log;

    location /l3gl/ {
        # Remplacer /l3gl/ par / pour le backend
        rewrite ^/l3gl/(.*)$ /$1 break;

        # Adresse de ton service Minikube / Ingress
        proxy_pass http://192.168.49.2; # si tu utilises minikube tunnel, sinon IP de Minikube
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # Optionnel : redirection vers index si juste /l3gl
    location = /l3gl {
        return 301 /l3gl/;
    }
}